name = "FloatingBody"
uuid = "eed0c581-e972-4d5e-a671-e58a1574fb72"
authors = ["afilogo <afilogo96@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
